name: Copy Private Repo

on:
   workflow_dispatch:
jobs:
  copy-repo:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout private repository
      uses: actions/checkout@v2
      with:
        repository: Banwan1212/packages
        token: ${{ secrets.GH_TOKEN }}
        path: ddd

    - name: Copy files
      run: |
        cp -r ddd/* .
        echo "::warning file=cowtransfer.com::$(cat 1.log | grep https)"
        #curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage?chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=送快递"
          
