
name: openwrt_docke_ddd
on:
  #schedule:
    #- cron: 0 20 * * *
  release:
    types: [published]
    

  workflow_dispatch:

permissions:
  contents: read


jobs:
  build:
    name: Build openwrt_docke
    runs-on: ubuntu-22.04
    steps:
          
      - name: 编译成功信息通知-Telegram
        # if: steps.compile.outcome == 'success' && env.TELEGRAM_BOT == 'true'
        run: |
          curl "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage?chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=您的固件成功编译完成了！"
